export const ActionType = {
  CHANGE_CITY: `CHANGE_CITY`,
  CHANGE_SORT_TYPE: `CHANGE_SORT_TYPE`,
  CHANGE_CARD_ON_HOVER: `CHANGE_CARD_ON_HOVER`,
  CHANGE_ACTIVE_OFFER: `CHANGE_ACTIVE_OFFER`,

  REQUIRED_AUTHORIZATION: `REQUIRED_AUTHORIZATION`,
  GET_USER: `GET_USER`,

  LOAD_OFFERS: `LOAD_OFFERS`,
  LOAD_REVIEWS: `LOAD_REVIEWS`,
  LOAD_OFFERS_NEARBY: `LOAD_OFFERS_NEARBY`,

  POST_REVIEW: `POST_REVIEW`,

  CATCH_ERROR: `CATCH_ERROR`,
  SET_REQUEST_STATUS: `SET_REQUEST_STATUS`
};
